### ISSUE TITLE
  // , Slides... can haz? 

### ISSUE THREAD

**Issue by v6** [michaelfolkson/bcoin-hackathon#4]
// , This isn't actually my issue, a wild lolcat appeared, and forced me to open it: 

![image](https://cloud.githubusercontent.com/assets/5750764/24494139/1a7c35fa-14e6-11e7-91b2-0902ab770dc5.png)

**Comment by michaelfolkson** [comment]
Lolcat requests must be accepted, even I know that much. https://www.slideshare.net/michaelfolkson/bcoin-hackathon-slides

**Comment by v6** [comment]
// , I think it wants them posted to the README.md file. 

![image](https://cloud.githubusercontent.com/assets/5750764/24575569/bbd0968e-165e-11e7-8151-8042fc96aa10.png)

![image](https://cloud.githubusercontent.com/assets/5750764/24575572/c7b6b4b0-165e-11e7-8d19-a79d480625db.png)

![image](https://cloud.githubusercontent.com/assets/5750764/24575574/d204878a-165e-11e7-99e9-48874799e2c5.png)

**Comment by michaelfolkson** [comment]
This a particularly demanding lolcat, ok...
